% -------------------------------------------------------------------
%  Generated by MATLAB on 23-Mar-2018 13:00:37
%  MATLAB version: 9.2.0.556344 (R2017a)
% -------------------------------------------------------------------
saveVarsMat = load('example_model_output.mat');

t = saveVarsMat.t; % <11333x1 double> too many elements

chi = saveVarsMat.chi; % <11333x1 double> too many elements

h = saveVarsMat.h; % <11333x1 double> too many elements

clear saveVarsMat;
