% -------------------------------------------------------------------
%  Generated by MATLAB on 10-Apr-2018 08:20:00
%  MATLAB version: 9.2.0.556344 (R2017a)
% -------------------------------------------------------------------
saveVarsMat = load('supermav_400_outof_5000.mat');

chi_out = saveVarsMat.chi_out; % <5000x3 double> too many elements

h_out = saveVarsMat.h_out; % <5000x3 double> too many elements

p_out = saveVarsMat.p_out; % <5000x1 double> too many elements

q_out = saveVarsMat.q_out; % <5000x1 double> too many elements

clear saveVarsMat;
